---
apiVersion: v1
kind: ConfigMap
metadata:
  name: registration-config
data:
  quarkus.opentelemetry.tracer.exporter.otlp.endpoint: http://jaeger-all-in-one-inmemory-collector.webhook-delivery-system.svc:4317
  quarkus.datasource.camel.jdbc.url: jdbc:postgresql://postgresql.postgresql.svc:5432/sampledb
---
apiVersion: v1
kind: Secret
metadata:
  name: registration-secret
stringData:
  quarkus.datasource.camel.username: admin
  quarkus.datasource.camel.password: admin
type: Opaque